services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: postech
    platform: linux/amd64
    environment:
      ACCEPT_EULA: "1"
      MSSQL_SA_PASSWORD: Fr00t_L00pth
    ports:
      - "2022:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql

volumes:
  sqlserver-data: